queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: npm install
  displayName: Install dependencies

- task: RichCodeNavIndexer@0
  inputs:
    serviceConnection: 'rich-code-nav-dev'
    languages: typescript
    githubServiceConnection: 'vsls-contrib'
    serviceEndpoint: 'https://vscloudkernel-dev.azurewebsites.net/api/v0.1'
