queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: npm install
  displayName: Install dependencies

- task: DotNetCoreInstaller@0
  displayName: 'Use .NET Core sdk 2.1.300'
  inputs:
    version: 2.1.300

- task: NuGetToolInstaller@0
  displayName: 'Use NuGet 4.3.0'

- task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
  displayName: 'VS IntelliNav Upload'
  inputs:
    vsckEndpoint: 'vscloudkernel-dev'
    nugetpat: 'vscloudkernel-nuget'
    language: javascript
    githubpat: 'vsls-contrib'
    nugetVersion: '0.1.806-alpha-g2adb5dd333'
