queue:
  name: Hosted VS2017

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.x'

- script: npm install
  displayName: Install dependencies

- task: vsintellinav.vsck-service-endpoint.build-task.upload-cache-build-task@0
  displayName: 'VS IntelliNav Upload'
  inputs:
    vsckEndpoint: 'vscloudkernel-dev-test'
    nugetpat: 'vscloudkernel-nuget'
    language: typescript
    githubpat: 'vsls-contrib'
